# Generated by Django 5.0.4 on 2024-06-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quiz_description_alter_quiz_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('C', 'C'), ('C++', 'C++'), ('Python', 'Python'), ('Java', 'Java'), ('PHP', 'PHP')], max_length=50),
        ),
    ]
