# Generated by Django 5.0.4 on 2024-06-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_quiz_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('C', 'C'), ('CPP', 'CPP'), ('Python', 'Python'), ('Java', 'Java'), ('PHP', 'PHP')], max_length=50),
        ),
    ]
